spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-security?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: 888888

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true